### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "h",
    "password": "h",
    "family": "h",
    "age": 12,
    "cellphone": "1",
    "active": false
}

### Get
GET http://localhost:3000/users/1
Content-Type: application/json